/* Generated By:JJTree: Do not edit this line. ASTnbre.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */


public
class ASTnbre extends SimpleNode {
	// Ajout d'une variable
	private int nombre;
	
  public ASTnbre(int id) {
    super(id);
  }

  public ASTnbre(MiniJaja p, int id) {
    super(p, id);
  }

  // Ajout de méthodes pour récuperer une valeur
  public void setValeur(int nb){
	this.nombre=nb;
  }
  
  public int getValeur(){
	return this.nombre;
  }
  
  /** Accept the visitor. **/
  public Object jjtAccept(MiniJajaVisitor visitor, Object data) throws MiniJajaVisitorException {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=6facc13a419d813d94a9e61714645fb6 (do not edit this line) */
