/* Generated By:JavaCC: Do not edit this line. MiniJajaVisitor.java Version 5.0 */
public interface MiniJajaVisitor
{
  public Object visit(SimpleNode node, Object data) throws MiniJajaVisitorException;
  public Object visit(ASTclasse node, Object data) throws MiniJajaVisitorException;
  public Object visit(ASTident node, Object data) throws MiniJajaVisitorException;
  public Object visit(ASTdecls node, Object data) throws MiniJajaVisitorException;
  public Object visit(ASTvnil node, Object data) throws MiniJajaVisitorException;
  public Object visit(ASTcst node, Object data) throws MiniJajaVisitorException;
  public Object visit(ASTtableau node, Object data) throws MiniJajaVisitorException;
  public Object visit(ASTmethode node, Object data) throws MiniJajaVisitorException;
  public Object visit(ASTvar node, Object data) throws MiniJajaVisitorException;
  public Object visit(ASTvars node, Object data) throws MiniJajaVisitorException;
  public Object visit(ASTomega node, Object data) throws MiniJajaVisitorException;
  public Object visit(ASTmain node, Object data) throws MiniJajaVisitorException;
  public Object visit(ASTentetes node, Object data) throws MiniJajaVisitorException;
  public Object visit(ASTenil node, Object data) throws MiniJajaVisitorException;
  public Object visit(ASTentete node, Object data) throws MiniJajaVisitorException;
  public Object visit(ASTinstrs node, Object data) throws MiniJajaVisitorException;
  public Object visit(ASTinil node, Object data) throws MiniJajaVisitorException;
  public Object visit(ASTretour node, Object data) throws MiniJajaVisitorException;
  public Object visit(ASTtantque node, Object data) throws MiniJajaVisitorException;
  public Object visit(ASTsi node, Object data) throws MiniJajaVisitorException;
  public Object visit(ASTappelI node, Object data) throws MiniJajaVisitorException;
  public Object visit(ASTaffectation node, Object data) throws MiniJajaVisitorException;
  public Object visit(ASTsomme node, Object data) throws MiniJajaVisitorException;
  public Object visit(ASTincrement node, Object data) throws MiniJajaVisitorException;
  public Object visit(ASTtab node, Object data) throws MiniJajaVisitorException;
  public Object visit(ASTlistexp node, Object data) throws MiniJajaVisitorException;
  public Object visit(ASTexnil node, Object data) throws MiniJajaVisitorException;
  public Object visit(ASTnon node, Object data) throws MiniJajaVisitorException;
  public Object visit(ASTneg node, Object data) throws MiniJajaVisitorException;
  public Object visit(ASTet node, Object data) throws MiniJajaVisitorException;
  public Object visit(ASTou node, Object data) throws MiniJajaVisitorException;
  public Object visit(ASTegal node, Object data) throws MiniJajaVisitorException;
  public Object visit(ASTinf node, Object data) throws MiniJajaVisitorException;
  public Object visit(ASTsup node, Object data) throws MiniJajaVisitorException;
  public Object visit(ASTplus node, Object data) throws MiniJajaVisitorException;
  public Object visit(ASTmoins node, Object data) throws MiniJajaVisitorException;
  public Object visit(ASTmult node, Object data) throws MiniJajaVisitorException;
  public Object visit(ASTdiv node, Object data) throws MiniJajaVisitorException;
  public Object visit(ASTvrai node, Object data) throws MiniJajaVisitorException;
  public Object visit(ASTfaux node, Object data) throws MiniJajaVisitorException;
  public Object visit(ASTappelE node, Object data) throws MiniJajaVisitorException;
  public Object visit(ASTnbre node, Object data) throws MiniJajaVisitorException;
  public Object visit(ASTrien node, Object data) throws MiniJajaVisitorException;
  public Object visit(ASTentier node, Object data) throws MiniJajaVisitorException;
  public Object visit(ASTbooleen node, Object data) throws MiniJajaVisitorException;
}
/* JavaCC - OriginalChecksum=41931f677c230b0bad5edb3dbd03b0ca (do not edit this line) */
