/* Generated By:JavaCC: Do not edit this line. MiniJajaTreeConstants.java Version 5.0 */
public interface MiniJajaTreeConstants
{
  public int JJTCLASSE = 0;
  public int JJTIDENT = 1;
  public int JJTVOID = 2;
  public int JJTDECLS = 3;
  public int JJTVNIL = 4;
  public int JJTCST = 5;
  public int JJTTABLEAU = 6;
  public int JJTMETHODE = 7;
  public int JJTVAR = 8;
  public int JJTVARS = 9;
  public int JJTOMEGA = 10;
  public int JJTMAIN = 11;
  public int JJTENTETES = 12;
  public int JJTENIL = 13;
  public int JJTENTETE = 14;
  public int JJTINSTRS = 15;
  public int JJTINIL = 16;
  public int JJTRETOUR = 17;
  public int JJTTANTQUE = 18;
  public int JJTSI = 19;
  public int JJTAPPELI = 20;
  public int JJTAFFECTATION = 21;
  public int JJTSOMME = 22;
  public int JJTINCREMENT = 23;
  public int JJTTAB = 24;
  public int JJTLISTEXP = 25;
  public int JJTEXNIL = 26;
  public int JJTNON = 27;
  public int JJTNEG = 28;
  public int JJTET = 29;
  public int JJTOU = 30;
  public int JJTEGAL = 31;
  public int JJTINF = 32;
  public int JJTSUP = 33;
  public int JJTPLUS = 34;
  public int JJTMOINS = 35;
  public int JJTMULT = 36;
  public int JJTDIV = 37;
  public int JJTVRAI = 38;
  public int JJTFAUX = 39;
  public int JJTAPPELE = 40;
  public int JJTNBRE = 41;
  public int JJTRIEN = 42;
  public int JJTENTIER = 43;
  public int JJTBOOLEEN = 44;


  public String[] jjtNodeName = {
    "classe",
    "ident",
    "void",
    "decls",
    "vnil",
    "cst",
    "tableau",
    "methode",
    "var",
    "vars",
    "omega",
    "main",
    "entetes",
    "enil",
    "entete",
    "instrs",
    "inil",
    "retour",
    "tantque",
    "si",
    "appelI",
    "affectation",
    "somme",
    "increment",
    "tab",
    "listexp",
    "exnil",
    "non",
    "neg",
    "et",
    "ou",
    "egal",
    "inf",
    "sup",
    "plus",
    "moins",
    "mult",
    "div",
    "vrai",
    "faux",
    "appelE",
    "nbre",
    "rien",
    "entier",
    "booleen",
  };
}
/* JavaCC - OriginalChecksum=1e941296a07bbfa3025a6515ba02f9d2 (do not edit this line) */
