/* Generated By:JJTree: Do not edit this line. ASTJCIdent.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTJCIdent extends SimpleNode {
  private String ident;
	
  public ASTJCIdent(int id) {
    super(id);
  }

  public ASTJCIdent(JajaCode p, int id) {
    super(p, id);
  }
  
  public void setValeur(String str){
	this.ident=str;
  }
	  
  public String getValeur(){
	return this.ident;
  }

  /** Accept the visitor. **/
  public Object jjtAccept(JajaCodeVisitor visitor, Object data) throws JajaCodeVisitorException {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=056165213c0948b13627ff85e52884d9 (do not edit this line) */
