/* Generated By:JJTree: Do not edit this line. ASTJCType.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTJCType extends SimpleNode {
  private String type;

  public ASTJCType(int id) {
    super(id);
  }

  public ASTJCType(JajaCode p, int id) {
    super(p, id);
  }

  public void setValeur(String str){
	this.type=str;
  }
	  
  public String getValeur(){
	return this.type;
  }
  /** Accept the visitor. **/
  public Object jjtAccept(JajaCodeVisitor visitor, Object data) throws JajaCodeVisitorException {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=4e7c6c27fb3584a1de5cb112054d0114 (do not edit this line) */
