/* Generated By:JJTree: Do not edit this line. ASTJajaCode.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTJajaCode extends SimpleNode {
  public ASTJajaCode(int id) {
    super(id);
  }

  public ASTJajaCode(JajaCode p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JajaCodeVisitor visitor, Object data) throws JajaCodeVisitorException {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=e9c5ed6a7bd3bdd2a8fcaa0f051a86e3 (do not edit this line) */
