/* Generated By:JJTree: Do not edit this line. ASTJCFaux.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTJCFaux extends SimpleNode {
  public ASTJCFaux(int id) {
    super(id);
  }

  public ASTJCFaux(JajaCode p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JajaCodeVisitor visitor, Object data) throws JajaCodeVisitorException {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=8b33538db5ea8d507b82a4091ab13f08 (do not edit this line) */
