/* Generated By:JJTree: Do not edit this line. ASTJCSorte.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTJCSorte extends SimpleNode {
  private String sorte;
	
  public ASTJCSorte(int id) {
    super(id);
  }

  public ASTJCSorte(JajaCode p, int id) {
    super(p, id);
  }

  public void setValeur(String str){
	this.sorte=str;
  }
	  
  public String getValeur(){
	return this.sorte;
  }

  /** Accept the visitor. **/
  public Object jjtAccept(JajaCodeVisitor visitor, Object data) throws JajaCodeVisitorException {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=9bf07bff88de4545c67097fa63fe2250 (do not edit this line) */
