/* Generated By:JavaCC: Do not edit this line. JajaCodeTreeConstants.java Version 5.0 */
public interface JajaCodeTreeConstants
{
  public int JJTVOID = 0;
  public int JJTJAJACODE = 1;
  public int JJTJCNIL = 2;
  public int JJTINIT = 3;
  public int JJTSWAP = 4;
  public int JJTNEW = 5;
  public int JJTNEWARRAY = 6;
  public int JJTINVOKE = 7;
  public int JJTRETURN = 8;
  public int JJTPUSH = 9;
  public int JJTPOP = 10;
  public int JJTLOAD = 11;
  public int JJTALOAD = 12;
  public int JJTSTORE = 13;
  public int JJTASTORE = 14;
  public int JJTIF = 15;
  public int JJTGOTO = 16;
  public int JJTINC = 17;
  public int JJTAINC = 18;
  public int JJTNOP = 19;
  public int JJTJCSTOP = 20;
  public int JJTJCIDENT = 21;
  public int JJTJCTYPE = 22;
  public int JJTJCSORTE = 23;
  public int JJTJCVRAI = 24;
  public int JJTJCFAUX = 25;
  public int JJTNEG = 26;
  public int JJTNOT = 27;
  public int JJTADD = 28;
  public int JJTSUB = 29;
  public int JJTMUL = 30;
  public int JJTDIV = 31;
  public int JJTCMP = 32;
  public int JJTSUP = 33;
  public int JJTINF = 34;
  public int JJTOR = 35;
  public int JJTAND = 36;
  public int JJTJCNBRE = 37;


  public String[] jjtNodeName = {
    "void",
    "JajaCode",
    "JCNil",
    "Init",
    "Swap",
    "New",
    "NewArray",
    "Invoke",
    "Return",
    "Push",
    "Pop",
    "Load",
    "ALoad",
    "Store",
    "AStore",
    "If",
    "Goto",
    "Inc",
    "AInc",
    "Nop",
    "JCStop",
    "JCIdent",
    "JCType",
    "JCSorte",
    "JCVrai",
    "JCFaux",
    "Neg",
    "Not",
    "Add",
    "Sub",
    "Mul",
    "Div",
    "Cmp",
    "Sup",
    "Inf",
    "Or",
    "And",
    "JCNbre",
  };
}
/* JavaCC - OriginalChecksum=cc621a2688a7e40fe142eb917ff1ca62 (do not edit this line) */
