/* Generated By:JavaCC: Do not edit this line. JajaCodeVisitor.java Version 5.0 */
public interface JajaCodeVisitor
{
  public Object visit(SimpleNode node, Object data) throws JajaCodeVisitorException;
  public Object visit(ASTJajaCode node, Object data) throws JajaCodeVisitorException;
  public Object visit(ASTJCNil node, Object data) throws JajaCodeVisitorException;
  public Object visit(ASTInit node, Object data) throws JajaCodeVisitorException;
  public Object visit(ASTSwap node, Object data) throws JajaCodeVisitorException;
  public Object visit(ASTNew node, Object data) throws JajaCodeVisitorException;
  public Object visit(ASTNewArray node, Object data) throws JajaCodeVisitorException;
  public Object visit(ASTInvoke node, Object data) throws JajaCodeVisitorException;
  public Object visit(ASTReturn node, Object data) throws JajaCodeVisitorException;
  public Object visit(ASTPush node, Object data) throws JajaCodeVisitorException;
  public Object visit(ASTPop node, Object data) throws JajaCodeVisitorException;
  public Object visit(ASTLoad node, Object data) throws JajaCodeVisitorException;
  public Object visit(ASTALoad node, Object data) throws JajaCodeVisitorException;
  public Object visit(ASTStore node, Object data) throws JajaCodeVisitorException;
  public Object visit(ASTAStore node, Object data) throws JajaCodeVisitorException;
  public Object visit(ASTIf node, Object data) throws JajaCodeVisitorException;
  public Object visit(ASTGoto node, Object data) throws JajaCodeVisitorException;
  public Object visit(ASTInc node, Object data) throws JajaCodeVisitorException;
  public Object visit(ASTAInc node, Object data) throws JajaCodeVisitorException;
  public Object visit(ASTNop node, Object data) throws JajaCodeVisitorException;
  public Object visit(ASTJCStop node, Object data) throws JajaCodeVisitorException;
  public Object visit(ASTJCIdent node, Object data) throws JajaCodeVisitorException;
  public Object visit(ASTJCType node, Object data) throws JajaCodeVisitorException;
  public Object visit(ASTJCSorte node, Object data) throws JajaCodeVisitorException;
  public Object visit(ASTJCVrai node, Object data) throws JajaCodeVisitorException;
  public Object visit(ASTJCFaux node, Object data) throws JajaCodeVisitorException;
  public Object visit(ASTNeg node, Object data) throws JajaCodeVisitorException;
  public Object visit(ASTNot node, Object data) throws JajaCodeVisitorException;
  public Object visit(ASTAdd node, Object data) throws JajaCodeVisitorException;
  public Object visit(ASTSub node, Object data) throws JajaCodeVisitorException;
  public Object visit(ASTMul node, Object data) throws JajaCodeVisitorException;
  public Object visit(ASTDiv node, Object data) throws JajaCodeVisitorException;
  public Object visit(ASTCmp node, Object data) throws JajaCodeVisitorException;
  public Object visit(ASTSup node, Object data) throws JajaCodeVisitorException;
  public Object visit(ASTInf node, Object data) throws JajaCodeVisitorException;
  public Object visit(ASTOr node, Object data) throws JajaCodeVisitorException;
  public Object visit(ASTAnd node, Object data) throws JajaCodeVisitorException;
  public Object visit(ASTJCNbre node, Object data) throws JajaCodeVisitorException;
}
/* JavaCC - OriginalChecksum=8ab0f442622e479ee245257214939ad8 (do not edit this line) */
